CornellNLP/ConvoKit

convokit/tests/text_processing/test_textToArcs.py, convokit/tests/util.py
A few things I want to bring up:
1. I'm realizing that writing unit tests that cover all code paths will take a huge amount of work. The `TextParser` took me a while, following that approach. I've opted to start writing tests that have less coverage but cover the main options that a given `Transformer` provides. So in the `TextToArcs` case, I'm writing tests for the default options, the `use_start` option, and the `root_only` option, but I haven't thoroughly tested the arc parsing logic. Does that sound reasonable for an initial pass of testing?
1. I don't have a strong enough grasp on dependency parsing to verify that the current outputs are correct; I've simply written tests that assume the current outputs are good. Can you point me to any resources on dependency parsing so I can know …
=> Add tests for TextToArcs

examples/converting_movie_corpus.ipynb
I spot a small typo in one of the examples. I believe it is necessary to correct it because it is the name of one of Utterance's attributes. There should be no changes in the output.
=> fix a typo

convokit/tests/bag_of_words/test_bow_transformer.py
Changed `FakeVectorizer` to return a matrix instead of vectors. Also learned that `coo_matrix` is a much more readable way to construct sparse matrices!
=> Fix BoWTransformer test

convokit/model/utterance.py
Enforces that the utterance text is a string. If None, then the text is the empty string. If some non-string object, then it gets typecast into a string.
=> Typecheck for utterance text

convokit/model/corpus.py, convokit/model/corpusHelper.py, convokit/tests/general/test_from_pandas.py, requirements.txt
In response to #69. 
Added a static method in the corpus class to create a corpus object from speakers, utterances and conversations dataframes. Also added helper functions to extract required metadata from the dataframes.
Utterances DataFrame is expected to contain all primary fields as columns. Speakers and Conversations are expected to have an "id" column; metadata columns are optional for all dataframes. Metadata columns are expected to have a "meta" prefix, as specified in #69.
=> Added 'from_pandas' method to create Corpus from DataFrames.

convokit/paired_prediction/pairer.py, doc/source/pairedprediction.rst, doc/source/pairer.rst
Separates PairedPrediction documentation into two parts: doc file for Pairer transformer and doc file for PairedPrediction and PairedVectorPrediction transformers. Each of the two files links to the other. In the Transformers/Analysis tree in the documentation site, we still have Paired Prediction doc (with the two paired prediction transformers).
=> Pairer doc update

.github/workflows/continuous-integration.yml, README.md, docs/source/troubleshooting.rst, docs/source/tutorial.rst, setup.py
Python 3.6 has reached its [end of life](https://endoflife.date/python), meaning packages in general will stop making updates to support it. We should accordingly drop support as well, as maintaining support for Python 3.6 will lead to dependency issues as other packages drop support for it.
This has already happened for our `clean-text` dependency: https://github.com/CornellNLP/ConvoKit/pull/170#issuecomment-1186366428.
Further context re: `clean-text`
As of `v0.6.0`, `clean-text` actually correctly sets its requirements to an older version of emoji. However, right now, when running the 3.6 workflow, it attempts to install `v0.5.0` instead, which installs the latest emoji (aka 2.0.0). The reason it does this is because `v0.6.0` does not support Python 3.6, as of 6 months ago, which …
=> Drop support for Python 3.6

.github/workflows/rsync-download-config.yml
We need to update `download_config.json` on the server any time a change happens to `download_config.json` in repo. 
Since all the older ConvoKit versions point to https://zissou.infosci.cornell.edu/convokit/datasets/download_config.json, we have keep this up-to-date with repo.
This PR adds a workflow to `rsync` the repo download config to server. The original path will be soft-linked to this rsync output path.
As described.
=> Add workflow to sync download_config.json

convokit/classifier/classifier.py, convokit/coordination/coordination.py, convokit/coordination/coordinationScore.py, convokit/expected_context_framework/demos/demo_text_pipelines.py, convokit/forecaster/forecasterModel.py, convokit/hyperconvo/hyperconvo.py, convokit/model/__init__.py, convokit/model/conversation.py, convokit/model/corpus.py, convokit/model/corpusComponent.py, convokit/model/speaker.py, convokit/model/user.py, convokit/model/utterance.py, convokit/paired_prediction/pairedPrediction.py, convokit/paired_prediction/pairer.py, convokit/phrasing_motifs/phrasingMotifs.py, convokit/prompt_types/promptTypeWrapper.py, convokit/ranker/ranker.py, convokit/tests/phrasing_motifs/test_questionSentences.py, convokit/tests/util.py
In preparation for ConvoKit 3.0, we are removing deprecated arguments and functions, such as:
- The `User` component, and all `user` methods, e.g. `has_user`, `get_user`, `iter_users`, `get_usernames`
- The `name` arg in `Speaker`
- The `root` arg in `Utterance`
- `get_info` and `set_info` -- in favor of `add_meta` and `retrieve_meta`
- Various deprecated args in analysis transformers
This cleans up the API (see #85) and simplifies development. ConvoKit 3.0 -- aka major version update -- is the right time for these constructors / methods to be cleaned up.
Tested through CI.
=> Remove deprecated args / funcs

convokit/expected_context_framework/col_normed_tfidf.py, convokit/hyperconvo/hyperconvo.py, convokit/model/corpus_helpers.py, convokit/politeness_collections/politeness_api/features/vectorizer.py, convokit/speakerConvoDiversity/speakerConvoDiversity.py, convokit/speakerConvoDiversity/speakerConvoDiversity2.py, convokit/speaker_convo_helpers/speaker_convo_attrs.py, convokit/speaker_convo_helpers/speaker_convo_lifestage.py, docs/source/wiki.rst
Fixed  license information for wiki-corpus in documentation.
=> documentation fix for wiki-corpus license 

examples/Introduction_to_ConvoKit.ipynb
Grammar correction to `Introduction_to_ConvoKit.ipynb`.
A small grammatic mistake, which is disturbing when going through the introduction.
By rerunning the script. It's just a comment change.
=> A grammar correction to Introduction_to_ConvoKit.ipynb

convokit/expected_context_framework/expected_context_model.py
This PR includes small fixes to the Expected Context Transformer Model to account for changes in numpy and sklearn dependencies. 
1. Change use of sklearn `normalize` to ensure we are passing in numpy array and not numpy matrix since use of `normalize` and other linear algebra operations for matrices are being deprecated [here](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html). 
2. Set `allow_pickle` field to True when loading Expected Context saved files since they contain objects. This field is now default to False as of numpy version 1.16.3 [here](https://numpy.org/devdocs/reference/generated/numpy.load.html). 
Manually.
Note the change in `np.load` may affect loading of other models if they save pickled data.
=> Small fixes for expected context transformer model

README.md, docs/source/awry_cmv.rst
=> CMV Corpus Link Typo Fix

README.md
=> Fix broken hypergraph demo link

.github/workflows/continuous-integration.yml, README.md, docs/source/troubleshooting.rst, setup.py
Updated `setup.py` and `.github` to support newer versions of python. Now CI will run against build on 3.11, 3.12, and 3.7, 3.8 are removed.
3.8 reaching EOL 10/7/2024
=> Towards Newer Versions of Python

.github/workflows/continuous-integration.yml, README.md, docs/source/troubleshooting.rst, setup.py
Updated `setup.py` and `.github` to support newer versions of python. Now CI will run against build on 3.11, 3.12, and 3.7, 3.8 are removed.
python 3.8 reaching EOL 10/7/2024, dependency packages (such as spacy) stop supporting python <3.9.
=> Towards Newer Version of Python

setup.py
Require numpy 2.0.0+ since spacy 3.8.2 is build against numpy 2.0+
=> fixing numpy version to be 2.0.0+

convokit/util.py
Fixes corpus download issues from #294 . Some corpora place files directly in the root of the ZIP, while others contain a top-level directory. This update adds logic to handle both formats, ensuring correct extraction and saving to local directories.
=> Corpus download issues

convokit/forecaster/README.md, docs/source/forecaster.rst
This Pull Request updates the evaluation results of 14 forecasting models on the CGA-Wikiconv benchmark. The updated results reflect the experiments conducted with the standardized evaluation pipeline in ConvoKit.
=> Update CGA benchmark for Wikipedia Corpus

convokit/__init__.py, convokit/forecaster/TransformerDecoderModel.py, convokit/forecaster/TransformerEncoderModel.py, convokit/forecaster/__init__.py, convokit/pivotal_framework/__init__.py, convokit/pivotal_framework/pivotal.py, convokit/redirection/__init__.py, convokit/redirection/config.py, convokit/redirection/gemmaLikelihoodModel.py, convokit/redirection/preprocessing.py, convokit/tests/run_all_tests.py, convokit/utterance_likelihood/__init__.py, convokit/utterance_likelihood/utteranceLikelihood.py, convokit/utterance_simulator/__init__.py, convokit/utterance_simulator/unslothUtteranceSimulatorModel.py, convokit/utterance_simulator/util.py, requirements-dev.txt
- Implemented lazy loading: Core modules imported immediately, others loaded on first access
- Modules' error handling are done by modules themselves, and would only be displayed if the module is imported
- Moved LLM dependency package handling from script files to module __init__.py files
- Replaced print statements with proper ImportError raising
=> implement lazy loading
